### ISSUE TITLE
Add page in tag permalink

### ISSUE THREAD

**Issue by ghost** [solution-loisir/eleventy-deep-pagination#1]
Hello
Thanks for the solution to this problem
I want the url tags to look like this:
**/tags/book/page/1**
Now it looks like this:
**/tags/book/1**

**Comment by solution-loisir** [comment]
Hi @iamsavadkoohi, you probably want to adjust `permalink` accordingly. Maybe try in the front matter:
```yaml
permalink: tags/{{ tag.tagName }}/{{ ("page/" + tag.pageNumber + 1 + "/") if tag.pageNumber }}
```

**Comment by solution-loisir** [comment]
I will be closing this issue since the account of the initiator seems to have been deleted and the solution in the comment should be satisfactory.
